In [1]:
import os
import pandas as pd
import numpy as np

In [4]:
data_path = os.path.join("..", "data", "student_data.csv")
if not os.path.exists(data_path):
    data_path = os.path.join("data", "student_data.csv")
if not os.path.exists(data_path):
    data_path = "student_data.csv"

df = pd.read_csv(data_path)

In [5]:
print(f"Dataset Shape: {df.shape[0]} rows, {df.shape[1]} columns")

Dataset Shape: 6607 rows, 20 columns

In [6]:
print("\n--- First 3 Rows ---")
display(df.head(3))

--- First 3 Rows ---

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74

In [7]:
print("\n--- Last 3 Rows ---")
display(df.tail(3))

--- Last 3 Rows ---

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [9]:
df.describe().round(2)

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.00,6607.00,6607.00,6607.00,6607.00,6607.00,6607.00
mean,19.98,79.98,7.03,75.07,1.49,2.97,67.24
std,5.99,11.55,1.47,14.40,1.23,1.03,3.89
min,1.00,60.00,4.00,50.00,0.00,0.00,55.00
25%,16.00,70.00,6.00,63.00,1.00,2.00,65.00
50%,20.00,80.00,7.00,75.00,1.00,3.00,67.00
75%,24.00,90.00,8.00,88.00,2.00,4.00,69.00
max,44.00,100.00,10.00,100.00,8.00,6.00,101.00

In [10]:
display(df.describe(include=['object']))

,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Motivation_Level,Internet_Access,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender
count,6607,6607,6607,6607,6607,6607,6529,6607,6607,6607,6517,6540,6607
unique,3,3,2,3,2,3,3,2,3,2,3,3,2
top,Medium,Medium,Yes,Medium,Yes,Low,Medium,Public,Positive,No,High School,Near,Male
freq,3362,3319,3938,3351,6108,2672,3925,4598,2638,5912,3223,3884,3814

In [11]:
print("--- Unique Categories per Column ---")
for col in df.select_dtypes(include=['object']).columns:
    unique_vals = list(df[col].dropna().unique())
    print(f"{col:<28}: {len(unique_vals)} unique -> {unique_vals}")

--- Unique Categories per Column ---
Parental_Involvement        : 3 unique -> ['Low', 'Medium', 'High']
Access_to_Resources         : 3 unique -> ['High', 'Medium', 'Low']
Extracurricular_Activities  : 2 unique -> ['No', 'Yes']
Motivation_Level            : 3 unique -> ['Low', 'Medium', 'High']
Internet_Access             : 2 unique -> ['Yes', 'No']
Family_Income               : 3 unique -> ['Low', 'Medium', 'High']
Teacher_Quality             : 3 unique -> ['Medium', 'High', 'Low']
School_Type                 : 2 unique -> ['Public', 'Private']
Peer_Influence              : 3 unique -> ['Positive', 'Negative', 'Neutral']
Learning_Disabilities       : 2 unique -> ['No', 'Yes']
Parental_Education_Level    : 3 unique -> ['High School', 'College', 'Postgraduate']
Distance_from_Home          : 3 unique -> ['Near', 'Moderate', 'Far']
Gender                      : 2 unique -> ['Male', 'Female']

In [12]:
null_counts = df.isnull().sum()
missing_df = pd.DataFrame({
    'Missing_Count': null_counts[null_counts > 0],
    'Percentage (%)': (null_counts[null_counts > 0] / len(df) * 100).round(2)
})

print("--- Columns with Missing Values ---")
display(missing_df)

--- Columns with Missing Values ---

                          Missing_Count  Percentage (%)
Teacher_Quality                      78            1.18
Parental_Education_Level             90            1.36
Distance_from_Home                   67            1.01